# This workflow will do a clean install of node dependencies and run tests

name: CI
on: [pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn test
